server:
  port: 8085
  servlet:
    context-path: /merchant
error:
  include-message: always

paygenius:
  url:
    baseUrl: https://developer.paygenius.co.za/pg/api
    createPayment: /create
    createEfyPayment: /create/eft
