server:
    port: 8085
    servlet:
        context-path: /merchant
error:
    include-message: always

paygenius:
    endpoint: https://developer.paygenius.co.za/pg/api/v2/payment/create
    feign-url: https://developer.paygenius.co.za/pg/api/v2/payment